version: '2.3'
services:
  postgis_container:
    image: "postgis/postgis:15-master"
    env_file:
      - .env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./pg_hba.conf:/var/lib/foo/pg_hba.conf
      - postgres-data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "hba_file=/var/lib/foo/pg_hba.conf" ]
    restart: always
  app:
    container_name: MyDudesGeoBackend
    build:
      context: .
      dockerfile: MyDudesGeoBackend.Dockerfile
    env_file:
      - .env
    environment:
      MYDUDES_TELEGRAM_BOT_TOKEN: $TELEGRAM_BOT_TOKEN
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis_container:5432/$POSTGRES_DB?sslmode=disable
      SPRING_DATASOURCE_USERNAME: $POSTGRES_USER
      SPRING_DATASOURCE_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "8080:8080"
    depends_on:
      - postgis_container
    restart: on-failure

volumes:
  postgres-data:
