version: '2.3'
services:
  postgis_container:
    image: "postgis/postgis:15-master"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  app:
    container_name: MyDudesGeoBackend
    build:
      context: .
      dockerfile: MyDudesGeoBackend.Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis_container:5432/postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgis_container
    restart: on-failure

volumes:
  postgres-data:
