version: '2.3'
services:
  postgres:
    image: "postgis/postgis:15-master"
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  app:
    container_name: MyDudesGeoBackend
    build:
      context: .
      dockerfile: MyDudesGeoBackend.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data:
