server:
  port: 9097
  servlet:
    session:
      cookie:
        same-site: none
        http-only: false
        secure: true
        name: JSESSIONID

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    #    hibernate:
    #      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:migrations/master.xml
    contexts: schema, data

mydudes:
  config:
    search:
      polygon:
        points: 16
      radius: 2000 #2km
    limit: 100
    categories:
      number: 3

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui