server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: none
        http-only: false
        secure: true
        name: JSESSIONID

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  #    url: jdbc:postgresql://localhost:5432/postgres
  #    username: postgres
  #    password: postgres
  jpa:
    #    properties:
    #      hibernate:
    #        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database-platform: org.hibernate.community.dialect.PostgreSQL95Dialect
  liquibase:
    change-log: classpath:migrations/master.xml
    contexts: schema, data

mydudes:
  telegram:
    bot:
      token:
  config:
    dobro:
      nickname: DobroRu
    search:
      polygon:
        points: 16
      radius: 2000 #2km
    limit: 20
    categories:
      number: 3

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui