server:
  port: 9097

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:migrations/master.xml
    contexts: schema, data

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui